version: '2.1'

services:
  localstack:
    privileged: true
    image: localstack/localstack
    build: 
      context: ./docker/localstack
    ports:
      - "4550-4595:4550-4595"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=kinesis,dynamodb,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_STREAM_NAME=reader-stream
      - KINESIS_STREAM_SHARDS=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock